default_context:
    full_name: Alexey Strokach
    email: alex.strokach@utoronto.ca
    git_url: https://gitlab.com
    git_username: ostrokach
    anaconda_username: ostrokach-forge
    pypi_username: ostrokach
    project_name: protein-adjacency-net
    project_slug: pagnn
    project_import: pagnn
    project_short_description: Protein Adjacency Graph Neural Network.
    docs_secret_key: ""
    version: "0.1.14"
    create_author_file: "y"
    open_source_license: MIT License
    _copy_without_render:
        - docs/output_toggle.tpl
        - docs/_templates/logo-image.html
