image: condaforge/linux-anvil:latest

stages:
  - build
  - test
  - deploy


# === Variables ===

variables:
  PACKAGE_VERSION: "0.1.0"
  DOCS_SECRET_KEY: "QQRcgz67PxJNFopTWGygv1Y9iqKle0Mb2rxFh22a9cc/"
  # Notebook environment variables
  PYTHON_VERSION: "3.6"
  SPARK_MASTER: "spark://192.168.6.210:7077"
  SPARK_ARGS:
    spark.executor.memory=128G,
    spark.sql.broadcastTimeout=3600,
    spark.driver.memory=16G,
    spark.driver.maxResultSize=16G
  DB_TYPE: "mysql"
  DB_PORT: "8331"


# === Pages ===

pages:
  stage: test
  before_script:
    # Create conda environment
    # (nice to use an environment in case we use `gitlab-runner exec shell`)
    - conda remove -n pages --all -yq || true
    - conda create -n pages -yq || true
    - conda install -n pages -yq
      git python pip ipython jupyter ipykernel pypandoc
    - source activate pages
    # Install pip packages
    - pip install -q
      git+https://github.com/arximboldi/sinusoidal-sphinx-theme.git
      sphinx sphinx_rtd_theme guzzle_sphinx_theme recommonmark
  script:
    # Generate notebooks.csv
    - ./scripts/create_notebook_table.py -i notebooks/ -o docs/notebooks.csv
    # Build pages
    - sphinx-build docs public/$DOCS_SECRET_KEY
    # Convert notebooks
    - mkdir -p public/$DOCS_SECRET_KEY/notebooks
    - ./scripts/convert_notebooks.sh notebooks/ public/$DOCS_SECRET_KEY/notebooks/


# === Deploy ===

.exec-notebook: &exec-notebook
  script:
    - jupyter nbconvert "notebooks/{NOTEBOOK_NAME}.ipynb"
      --to=html_ch
      --output=$NOTEBOOK_NAME.html
      --output-dir=logs/
      --template=docs/output_toggle.tpl
      --execute

deploy:
  stage: deploy
  variables:
    NOTEBOOK_NAME: deploy
  <<: *exec-notebook
  when: manual
