channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python
  - ipython
  # Jupyter
  - jupyter
  - jupyter_contrib_nbextensions
  - isort
  - psutil
  # Scientific Python
  - numpy
  - scipy
  - pandas
  - scikit-learn
  # Spark
  - pyspark
  - openjdk
  # PyTorch
  - pytorch::pytorch
