channels:
  # NB: conda-forge has to be first because it has the newest versions of everything
  - conda-forge
  - defaults
  - ostrokach-forge
  - kimlab
  - bioconda
  - pytorch
dependencies:
  # Binary utils
  - xsv
  - ripgrep
  - fd-find
  - ostrokach-forge::parallel
  # Python
  - python >=3.7
  - ipython
  # Jupyter
  - jupyter
  - jupyterlab
  - conda-forge::jupyter_contrib_nbextensions
  - isort
  - psutil
  - boltons
  - attrs
  - click
  - pyyaml
  # Scientific
  - defaults::numpy
  - scipy
  - pandas
  - numba
  - pyarrow >=0.11.1
  - scikit-learn
  - sqlalchemy
  - modeller =9.20
  - mdanalysis >=0.19.2
  # Plotting
  - matplotlib
  - matplotlib-venn
  - seaborn
  # Spark
  - findspark
  # Machine Learning
  - pytorch::pytorch >=1.0.0
  # KimLab
  - kmbio >=2.0.13
  - kmtools >=0.0.36
  # - pagnn
