package:
  name: pagnn
  version: 0.1.9

source:
  path: ../../

build:
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - click
    - tqdm
    - attrs
    - protobuf
    # Numerical Python
    - numpy
    - scipy
    - pandas
    - pyarrow >=0.10.*
    - numba
    - pytorch
    - tensorboardx
    - torchvision
    - scikit-learn
    # Biological Python
    - kmbio
    - kmtools
    - weblogo

test:
  source_files:
    - setup.cfg
    - tests
  requires:
    - pytest
    - pytest-cov
    - pytest-benchmark
    - hypothesis
  imports:
    - pagnn

# outputs:
#   - name: pagnn
#     type: conda
#   - type: wheel

about:
  home: https://gitlab.com/kimlab/pagnn
  license: MIT License
  summary: "Protein Adjacency Graph Neural Network."
