package:
  name: pagnn
  version: 0.1.12

source:
  path: ../../

build:
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - attrs
    - click
    - pyyaml
    # Numerical Python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - sqlalchemy
    - pyarrow >=0.11.*
    - numba
    - pytorch-nightly-cpu =1.0.0.dev20181001

test:
  source_files:
    - setup.cfg
    - tests
  requires:
    - pytest
    - pytest-cov
    - pytest-benchmark
    - hypothesis
  imports:
    - pagnn

# outputs:
#   - name: pagnn
#     type: conda
#   - type: wheel

about:
  home: https://gitlab.com/kimlab/pagnn
  license: MIT
  summary: "Protein Adjacency Graph Neural Network."
