{% set name = "pagnn" %}
{% set version = "0.1.6" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  path: ../

build:
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python
    - pandoc
    - pypandoc
  run:
    # Basic Python
    - python
    - click
    - tqdm
    # Numerical Python
    - numpy
    - scipy
    - pandas
    - pyarrow
    - numba
    - pytorch =0.3.*
    - torchvision
    - tensorboardx
    # Our packages
    - kmtools

test:
  requires:
    - pytest
    - pytest-cov
    - pytest-benchmark
  imports:
    - pagnn

outputs:
  - name: {{ name }}
    type: conda
  - type: wheel

about:
  home: http://gitlab.com/kimlab/pagnn
  license: MIT License
  summary: "A neural network trained to select real proteins that fold to the provided adjacency matrix."
