{% set name = "pagnn" %}
{% set version = "0.1.3.dev0" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  path: ../

build:
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python
    - pandoc
    - pypandoc
  run:
    - python
    - click
    - numpy
    - scipy
    - pyarrow
    - numba
    - pytorch
    - torchvision
    - kmtools
    - tqdm

test:
  requires:
    - flake8
    - isort
    - mypy
    - pytest
    - pytest-cov
    - pytest-benchmark
  imports:
    - pagnn

outputs:
  - name: {{ name }}
    type: conda
  - type: wheel

about:
  home: http://gitlab.com/kimlab/pagnn
  license: MIT License
  summary: "A neural network trained to select real proteins that fold to the provided adjacency matrix."
