{% set name = "pagnn" %}
{% set version = "0.1.9.dev" %}
{% set kmbio = "2.0.5" %}
{% set kmtools = "0.0.26" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  path: ../

build:
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python
    - pandoc
    - pypandoc
  run:
    # Basic Python
    - python
    - click
    - tqdm
    - attrs
    - protobuf
    # Numerical Python
    - numpy
    - scipy
    - pandas
    - pyarrow >=0.9.*
    - numba
    - torch-nightly ==2018.04.20
    - tensorboardx
    - torchvision
    - scikit-learn
    # Biological Python
    - kmbio =={{ kmbio }}
    - kmtools =={{ kmtools }}
    - weblogo

test:
  source_files:
    - setup.cfg
    - tests
  requires:
    - pytest
    - pytest-cov
    - pytest-benchmark
  imports:
    - pagnn

outputs:
  - name: {{ name }}
    type: conda
  - type: wheel

about:
  home: http://gitlab.com/kimlab/pagnn
  license: MIT License
  summary: "A neural network trained to select real proteins that fold to the provided adjacency matrix."
